---
- name: Install Python, Node.js and tools
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'python3-pip', 'python-pip', 'virtualenv', 'python3-setuptools', 'python3-dev', 'build-essential', 'libssl-dev', 'nodejs', 'npm' ]

- name: Install Vue CLI
  npm:
    name: "@vue/cli"
    global: yes
    state: latest

# - name: Install Vue CLI service
#   npm:
#     name: "@vue/cli-service"
#     global: yes
#     state: latest

- name: Create directory for app
  file:
    path: "/home/{{ username }}/to"
    state: directory

- name: copy api over to server
  copy:
    src: "{{ inventory_dir | dirname }}/to-server-api/"
    dest: "/home/{{ username }}/to/to-server-api/"
    owner: "{{ username }}"
    group: www-data

- name: copy frontend over to server
  copy:
    src: "{{ inventory_dir | dirname }}/to-tmcd-me/"
    dest: "/home/{{ username }}/to/to-tmcd-me/"
    owner: "{{ username }}"
    group: www-data