---
- name: Install Python, Node.js and tools
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'python3-pip', 'virtualenv', 'python3-setuptools', 'python3-dev', 'build-essential', 'libssl-dev', 'nodejs', 'npm' ]

- name: Install Vue CLI
  npm:
    name: "@vue/cli"
    global: yes
    state: latest

- name: Create directory for MySQL volume storage
  file:
    path: "/home/{{ username }}/to"
    state: directory

- name: copy project over to server
  copy:
    src: "{{ inventory_dir | dirname }}"
    dest: /home/{{ username }}/to/
    owner: "{{ username }}"
    group: www-data