---
- name: Install TO frontend, API, and configure NGINX
  hosts: all
  remote_user: root
  # become: yes
  # become_method: sudo

  roles:
    - common
    - docker
    - mysql
    - to-api
    - to-frontend
    - nginx