"""empty message

Revision ID: d3884280f8e1
Revises: 
Create Date: 2019-08-07 10:56:05.048454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3884280f8e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alias_alias'), 'alias', ['alias'], unique=True)
    op.create_index(op.f('ix_alias_target'), 'alias', ['target'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alias_target'), table_name='alias')
    op.drop_index(op.f('ix_alias_alias'), table_name='alias')
    op.drop_table('alias')
    # ### end Alembic commands ###
